### ISSUE TITLE
Cannot run on custom datasets

### ISSUE THREAD

**Issue by jubileekr** [hynnsk/HP#1]
Hello,

I tried to run your code on a custom dataset but it seems to fall into exception/error as unknown dataset. Do you have any remedy for this?

**Comment by hynnsk** [comment]
This code is tailored specifically to handle the cocostuff, cityscapes, and potsdam-3 datasets, as indicated in the /dataset/data.py file. If you wish to utilize it for a custom dataset, please note that an additional dataloader would be required.

If the error still occurs, it could be related to the CUDA version in use (my setup involves using CUDA 11.3).
Please let me know more information about the error that occurred.

**Comment by jubileekr** [comment]
Thank you for your prompt reply. I will try to see if I can add the dataloader.

**Comment by tanveer6715** [comment]
> Thank you for your prompt reply. I will try to see if I can add the dataloader.

Hi. Have you solved your problem? I am also facing error using my custom dataset.

**Comment by jubileekr** [comment]
Not yet. I am dealing with another model rn.

**Comment by innat-asj** [comment]
Hi @hynnsk, could you please add a section regarding how to use custom data on the readme page? Specifically, as it is unsupervised, how to construct the data loader for the hp model to handle only image data, without any target/mask, etc. I took a look at the cityscape data loader only, and it looks like the data loader also yields labels and masks. Thanks.
