### ISSUE TITLE
Usage of negative_mask_one

### ISSUE THREAD

**Issue by bio-mlhui** [hynnsk/HP#13]
Hi, your work is fantastic! I have one question to seek for your help.
In the `SupConLoss`, a `negative_mask_one` bool tensor is constructed and used for each sample in the batch:
```python
torch.scatter(torch.ones((split,batch_size), dtype=torch.float16), 1,
                                        torch.arange(split).view(-1,1),0).to(device)
``` 
Is it used to neglect self-token when training? For this tensor, it is of shape `hw bhw`, where `b` is the batch size, `hw` is the number of tokens for each sample in the batch. But zeros only appears at the first batch chunk in the second dimension, i.e. `negative_mask_one[:, hw:]` are all 1. When it is used for non-first sample in the batch, what is it effect?

Looking for your reply! Thanks in advance!

**Comment by hynnsk** [comment]
Hello,

I appreciate your interest in our work.

There is a code at the end of the SupConLoss to process another batch, like:
```
negative_mask_one = torch.roll(negative_mask_one, split, dims=1)
```

Here is an example of how it works. When I run the following code:
```
negative_mask_one = torch.scatter(torch.ones((4,12), dtype=torch.float16), 1, torch.arange(4).view(-1,1),0)
print (negative_mask_one)
negative_mask_one = torch.roll(negative_mask_one, 4, dims=1)
print (negative_mask_one)
```

The output is:
```
tensor([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=torch.float16)
tensor([[1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.]], dtype=torch.float16)
```

I hope this helps clarify the process.

Thank you.

**Comment by Xu-Huihui** [comment]
Sorry for my mistake that I overlook that line. Thanks so much!
