### ISSUE TITLE
data stuff

### ISSUE THREAD

**Issue by innat-asj** [hynnsk/HP#2]
In the [data/download](--debug), you set 4 datasets, but the [json-config](https://github.com/hynnsk/HP/tree/main/json/server) is only provided for one of the datasets (coco). Other seems missing, i.e. citycaps. 

Though in read-me, it's mentioned to [update](https://github.com/hynnsk/HP#training--evaluation) the datatype and data path. I followed that for citycaps data. After downloading this data set with the provided scripts, the file structure looks something like as follows:

![image](https://github.com/hynnsk/HP/assets/81627860/9d615c62-6d48-4e67-b425-eaccfa930523)

and update the json 

```python
data_type:"cityscapes"
data_path:"cityscapes/cityscapes"
```

Now, I run 

```python
python run.py --opt ./json/server/cocostuff.json --debug
```

I got the following error

```bash
  File "run.py", line 41, in run
    train_dataset = build_dataset(opt["dataset"], mode="train", model_type=opt["model"]["pretrained"]["model_type"])
  File "/home/jupyter/HP/build.py", line 185, in build_dataset
    pos_labels=False
  File "/home/jupyter/HP/dataset/data.py", line 529, in __init__
    target_transform=target_transform, **extra_args)
  File "/home/jupyter/HP/dataset/data.py", line 417, in __init__
    self.num_images = len(os.listdir(self.img_dir))
FileNotFoundError: [Errno 2] No such file or directory: 'data/Datasets/cityscapes/cityscapes/cropped/cityscapes_five_crop_0.5/img/train'
```

**Comment by DpDark** [comment]
> In the [data/download](--debug), you set 4 datasets, but the [json-config](https://github.com/hynnsk/HP/tree/main/json/server) is only provided for one of the datasets (coco). Other seems missing, i.e. citycaps.
> 
> Though in read-me, it's mentioned to [update](https://github.com/hynnsk/HP#training--evaluation) the datatype and data path. I followed that for citycaps data. After downloading this data set with the provided scripts, the file structure looks something like as follows:
> 
> ![image](https://user-images.githubusercontent.com/81627860/241870309-9d615c62-6d48-4e67-b425-eaccfa930523.png)
> 
> and update the json
> 
> ```python
> data_type:"cityscapes"
> data_path:"cityscapes/cityscapes"
> ```
> 
> Now, I run
> 
> ```python
> python run.py --opt ./json/server/cocostuff.json --debug
> ```
> 
> I got the following error
> 
> ```shell
>   File "run.py", line 41, in run
>     train_dataset = build_dataset(opt["dataset"], mode="train", model_type=opt["model"]["pretrained"]["model_type"])
>   File "/home/jupyter/HP/build.py", line 185, in build_dataset
>     pos_labels=False
>   File "/home/jupyter/HP/dataset/data.py", line 529, in __init__
>     target_transform=target_transform, **extra_args)
>   File "/home/jupyter/HP/dataset/data.py", line 417, in __init__
>     self.num_images = len(os.listdir(self.img_dir))
> FileNotFoundError: [Errno 2] No such file or directory: 'data/Datasets/cityscapes/cityscapes/cropped/cityscapes_five_crop_0.5/img/train'
> ```

Could you run it successfully on COCOStuff ? I meet the same problem on COCOStuff. Maybe this project lost some process code?

**Comment by hynnsk** [comment]
Hello. Thanks for your interest in our work.

We added cityscapes.json to json/server directory, so you can run on cityscapes dataset.

In addition, the error can be resolved if you modify the value of "crop_type" to null in json file.
Or, if you wish to run the code with five-cropped-data, please see src/crop_datasets.py in [STEGO](https://github.com/mhamilton723/STEGO) repository.

**Comment by innat-asj** [comment]
Thanks for the update.

I also needed to update [`model_type=opt["wandb"]["name"]`](https://github.com/hynnsk/HP/blob/0384b0321507a5d9ca3cea1836834d603dfec168/run.py#L89) to `model_type=opt["model"]["name"]`

**Comment by hynnsk** [comment]
Thank you !!
