### ISSUE TITLE
Multi GPUs Training

### ISSUE THREAD

**Issue by DpDark** [hynnsk/HP#3]
Hi

Now I just have several 3090 GPUs with 24GB RAM, but don't have the large memory GPU like A6000. So I want to ask if I can train this model on 3090 GPUs? I set the gpus in json file, but it seems not work.

**Comment by hynnsk** [comment]
Hi

Thanks for your interest, but the current code does not take into account multi-GPU setting.
An alternative would be to run with a lower batch size, but this may result in slight performance degradation.

Thank you.

**Comment by innat-asj** [comment]
What is the minimum VRAM required to make hp run? I tried with 16 gb with batch size 1, still OOM.

**Comment by hynnsk** [comment]
To run on COCO-stuff dataset, VRAM required for batch_size=64 and 32 is 32GB and 12GB, respectively.

In addition, to run with 16GB VRAM, batch_size=32 of val_loader in run.py should be modified to 16.

To summarize, we recommend setting the batch_size in json file to 32 and modifying the batch size of the val_loader in run.py to 16.

**Comment by DpDark** [comment]
> What is the minimum VRAM required to make hp run? I tried with 16 gb with batch size 1, still OOM.

I use the single 3090 with 24GB VRAM to train the model for batch_size=32 on cocostuff, it runs well in the first iterations but still meet the OOM problem in the later iterations. 12GB seems not enough for the 32 batch size.

![Screenshot from 2023-06-01 10-10-20](https://github.com/hynnsk/HP/assets/64478649/fbb4c41e-eb7c-4850-b93d-b71afb8e4c0c)
![Screenshot from 2023-06-01 10-17-23](https://github.com/hynnsk/HP/assets/64478649/75b31bbe-01a1-47d0-bbc9-5806d38f38f7)

**Comment by hynnsk** [comment]
@DpDark
Have you checked the batch_size of val_loader in main.py (line 52)?
Please make sure to set it to 16 or less.

**Comment by DpDark** [comment]
> @DpDark Have you checked the batch_size of val_loader in main.py (line 52)? Please make sure to set it to 16 or less.

Thanks, it runs well when the batch_size in val_loader set as 16 and it cost about 13GB VRAM.
