### ISSUE TITLE
How to get the segmentation result of the image

### ISSUE THREAD

**Issue by zxinlei** [hynnsk/HP#5]
Thanks for your work!
How to use the weight file I have trained to predict new pictures? 
Looking forward to your reply!

**Comment by hynnsk** [comment]
Hi, Thank you for your interest in my work.

Additional dataloader would be required If you wish to utilize it for a custom dataset,
because this code is tailored specifically to handle the cocostuff, cityscapes, and potsdam-3 datasets.

Thank you
