### ISSUE TITLE
The model from checkpoint is not match for current model

### ISSUE THREAD

**Issue by Ustinian-J** [hynnsk/HP#7]
Thank you for your work!
Before running run.py, I changed the "batch_size" from 64 to 32, getting a checkpoint named "ckpt.pth".
 
![image](https://github.com/hynnsk/HP/assets/67846400/4e389eab-9593-45d0-8928-db1274226723)
Now, when I try to run eval.py, some errors happened with state_dict just as belows:

"RuntimeError: Error(s) in loading state_dict for DinoFeaturizer:
	size mismatch for model.cls_token: copying a param with shape torch.Size([1, 1, 768]) from checkpoint, the shape in current model is torch.Size([1, 1, 384]).
	size mismatch for model.pos_embed: copying a param with shape torch.Size([1, 785, 768]) from checkpoint, the shape in current model is torch.Size([1, 785, 384]).
	size mismatch for model.patch_embed.proj.weight: copying a param with shape torch.Size([768, 3, 8, 8]) from checkpoint, the shape in current model is torch.Size([384, 3, 8, 8]).
	size mismatch for model.patch_embed.proj.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([384]).
	size mismatch for model.blocks.0.norm1.weight: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([384])."

There is also a capture:
![image](https://github.com/hynnsk/HP/assets/67846400/48a5abb7-ca99-421b-be81-7d76bfc46db3)

Hope for your help, thank you very much !

**Comment by hynnsk** [comment]
Hello,

I think that you set the 'model_type' in json file to 'vit_base' before running run.py.

If you trained with 'vit_base,' you should also set the 'model_type' in cocostuff_eval.json to 'vit_base.'

Thank you.

**Comment by Ustinian-J** [comment]
I'm really grateful to your reply, thank you very much!
